### PR TITLE
Addresses deprecation warning for s3_bucket_object resource

### PR DESCRIPTION
**Pull request by eemperor**

### CODE REVIEW

**Review by lorengordon — COMMENTED** [review]
Looks like the README could use the same update... I guess this project doesn't have a versions.tf, but this is a backwards-incompatible change that requires aws provider v4. Might be worth adding and `bumpversion major`.

**Comment by eemperor** [comment]
> 

Okay.  I'll make the updates.

**Review by lorengordon — APPROVED** [review]
Just a nit, but there are still some references to `aws_s3_bucket_object` in the README. Approving anyway, since it's an inconsistency but not a blocker.

**Comment by eemperor** [comment]
> Just a nit, but there are still some references to `aws_s3_bucket_object` in the README. Approving anyway, since it's an inconsistency but not a blocker.

Ah.  I was fixing the terraform-docs portion and must have dropped the changes for the names.  I'll fix it shortly in another PR.

**Pull request merged**
